// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAdSpaceFields {
  /** Link */
  link: string;

  /** Desktop image */
  desktopImage: Asset;

  /** Mobile image */
  mobileImage: Asset;
}

export interface IAdSpace extends Entry<IAdSpaceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "adSpace";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IArticleFields {
  /** Title */
  title: string;

  /** Slug */
  slug?: string | undefined;

  /** Publication Date */
  publicationDate?: string | undefined;

  /** Members Only */
  membersOnly: boolean;

  /** Author */
  author: IAuthor;

  /** Content */
  content: Document;

  /** Feature image */
  featureImage: Asset;

  /** Excerpt */
  excerpt: string;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAuthorFields {
  /** Name */
  name?: string | undefined;
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFeaturedEventsFields {
  /** Link (the URL of the event/workshop page) */
  link: string;

  /** Title (the name of the workshop) */
  title: string;
}

export interface IFeaturedEvents extends Entry<IFeaturedEventsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "featuredEvents";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPractitionersFields {
  /** name */
  name: string;

  /** bio */
  bio: string;

  /** email */
  email?: string | undefined;

  /** website */
  website?: string | undefined;

  /** photo */
  photo?: Asset | undefined;

  /** occupation */
  occupation: string;

  /** hidden */
  hidden?: boolean | undefined;
}

export interface IPractitioners extends Entry<IPractitionersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "practitioners";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IReviewsFields {
  /** Title */
  title: string;

  /** Blurb */
  blurb: string;

  /** Profile photo */
  profilePhoto?: Asset | undefined;

  /** Stars */
  stars: number;

  /** Author */
  author: string;

  /** Review date */
  date: string;
}

export interface IReviews extends Entry<IReviewsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "reviews";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITeamMembersFields {
  /** Name */
  name: string;

  /** Email */
  email?: string | undefined;

  /** Role / job title */
  role?: string | undefined;

  /** Profile image */
  photo?: Asset | undefined;

  /** Biography */
  bio: string;
}

export interface ITeamMembers extends Entry<ITeamMembersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "teamMembers";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVideosFields {
  /** link */
  link: string;

  /** Title */
  title: string;
}

export interface IVideos extends Entry<IVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "videos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IWorkshopsFields {
  /** Description */
  description?: Document | undefined;

  /** Header */
  header: string;

  /** Date of event */
  dateOfEvent: string;

  /** Excerpt */
  excerpt: string;

  /** Cost (in cents) */
  costInCents: number;

  /** featureImage */
  featureImage: Asset;

  /** Facilitator */
  facilitator: IPractitioners[];

  /** In person? */
  inPerson: boolean;

  /** Slug */
  slug: string;

  /** Related Event */
  relatedEvent?: string | undefined;
}

export interface IWorkshops extends Entry<IWorkshopsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "workshops";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "adSpace"
  | "article"
  | "author"
  | "featuredEvents"
  | "practitioners"
  | "reviews"
  | "teamMembers"
  | "videos"
  | "workshops";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
